// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TurboSkola.Data;

#nullable disable

namespace TurboSkola.Migrations
{
    [DbContext(typeof(UcivoDbContext))]
    [Migration("20260403120000_AddPairedConsonantsSettings")]
    partial class AddPairedConsonantsSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot pro design-time nástroje – runtime používá pouze atribut [Migration]
        }
    }
}
