// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TurboSkola.Data;

#nullable disable

namespace TurboSkola.Migrations
{
    [DbContext(typeof(UcivoDbContext))]
    [Migration("20260406120000_AddPreparedTrainingSortOrderAndArchive")]
    partial class AddPreparedTrainingSortOrderAndArchive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
